---

- name: install yum-utils
  yum:
    name: yum-utils
    state: present

- name: add docker repo
  shell: yum-config-manager --add-repo {{ docker.repo }}

- name: install docker
  yum:
    name: "{{ docker.name }}"
    state: present
    update_cache: True

- name: set systemd for docker
  systemd:
    name: docker
    state: started